[lint]
ignore = [
    "E701",    
    "E702",    
    "F401",    
    "F403",    
    "F811",    
    "EXE001",  
    "I001",    
    "BLE001",  
    "S110",    
    "RUF059",  
    "RUF012",  
    "RUF100",  
    "C401",    
    "C408",    
    "SIM102",  
]
